language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database PostItDb;' -U postgres

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=traviz CXX=g++-4.8