language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database postitdbtests;' -U postgres

script:
  - npm install
  - npm run client-test
  - npm run coverage
  - npm run test
  - npm run coverage