language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database postitdbtests;' -U postgres
  
script: 
  - npm install
  - npm run test
  - npm run coverage
after_success:
  - npm run coveralls