export const auth = {
  SUCCESS: 'AUTHENTICATION_SUCCESS',
  FAILURE: 'AUTHENTICATION_FAILURES'
};

export const group = {
  CREATE_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_FAILURE: 'CREATE_GROUP_FAILURE',
  LIST_SUCCESS: 'LIST_GROUP_SUCCESS',
  LIST_FAILURE: 'LIST_GROUP_FAILURE'
};

export const member = {
  ADD_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_FAILURE: 'ADD_MEMBER_FAILURE',
  LIST_SUCCESS: 'LIST_MEMBERS_SUCCSS',
  LIST_FAILURE: 'LIST_MEMBERS_FAILURE'
};

export const message = {
  CREATE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
  CREATE_FAILURE: 'CREATE_MESSAGE_FAILURE',
  LIST_SUCCESS: 'LIST_MESSAGES_SUCCESS',
  LIST_FAILURE: 'LIST_MESSAGES_FAILURE'
};
